### ISSUE TITLE
define program in grammar

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/fsl#5]

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#7](https://github.com/h1alexbel/fsl/issues/7), [#8](https://github.com/h1alexbel/fsl/issues/8) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel all 2 puzzles are solved here: [#7](https://github.com/h1alexbel/fsl/issues/7), [#8](https://github.com/h1alexbel/fsl/issues/8).
